# -*- coding: utf-8 -*-
"""Customer Intelligence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sku1VT4lcnedSt_nwd2Lix4GJY4uKcg9
"""

# Importing the things we need
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Load the csv file I uploaded
my_data = pd.read_csv('customer_reviews (1).csv')

# Checking if the data loaded correctly
print("Data loaded! Here are the first few rows:")
print(my_data.head())

# I am making two lists of words to help the computer understand the reviews
positive_words = ['great', 'excellent', 'love', 'fast', 'perfect', 'good', 'best', 'happy', 'amazing', 'nice']
negative_words = ['late', 'crack', 'cheap', 'worst', 'broke', 'waste', 'bad', 'terrible', 'broken', 'slow']

print("Word lists created!")

# This function looks at a review and decides if it is Good, Bad, or Okay
def check_feedback(review_text):
    review_text = str(review_text).lower() # make it lowercase

    score = 0
    # check for positive words
    for word in positive_words:
        if word in review_text:
            score = score + 1

    # check for negative words
    for word in negative_words:
        if word in review_text:
            score = score - 1

    # tell me the result
    if score > 0:
        return 'Happy'
    elif score < 0:
        return 'Unhappy'
    else:
        return 'Neutral'

print("Function is ready to use.")

# Now I am applying my function to every row in the 'review' column
my_data['Result'] = my_data['review'].apply(check_feedback)

# Let's see what happened
print(my_data[['review', 'Result']].head(10))

# Calculating some basic stats for the project
total_count = len(my_data)
average_stars = my_data['rating'].mean()
happy_count = len(my_data[my_data['Result'] == 'Happy'])
happy_percent = (happy_count / total_count) * 100

print("--- Project Stats ---")
print("Total Reviews analyzed:", total_count)
print("Average Rating:", round(average_stars, 2))
print("Percentage of Happy Customers:", round(happy_percent, 1), "%")

import plotly.graph_objects as go

# Making simple KPI cards to show the main numbers
fig_kpi = go.Figure()

fig_kpi.add_trace(go.Indicator(
    mode = "number",
    value = total_count,
    title = {"text": "Total Reviews"},
    domain = {'x': [0, 0.3], 'y': [0, 1]}
))

fig_kpi.add_trace(go.Indicator(
    mode = "number",
    value = average_stars,
    title = {"text": "Average Rating"},
    domain = {'x': [0.35, 0.65], 'y': [0, 1]}
))

fig_kpi.add_trace(go.Indicator(
    mode = "number",
    value = happy_percent,
    number = {'suffix': "%"},
    title = {"text": "Happy %"},
    domain = {'x': [0.7, 1], 'y': [0, 1]}
))

fig_kpi.show()

# Chart 1: Pie chart for results
fig1 = px.pie(my_data, names='Result', title='Distribution of Feedback',
             color='Result', color_discrete_map={'Happy':'green', 'Unhappy':'red', 'Neutral':'gray'})
fig1.show()

# Chart 2: Average rating per product
product_ratings = my_data.groupby('product')['rating'].mean().reset_index()
fig2 = px.bar(product_ratings, x='product', y='rating', title='Average Rating by Product', color='product')
fig2.show()

# Chart 3: Age distribution
fig3 = px.histogram(my_data, x='age', color='Result', title='Age of Customers vs Feedback', barmode='group')
fig3.show()

# Making a visual of the most common words
all_happy_text = " ".join(my_data[my_data['Result']=='Happy']['review'])
all_unhappy_text = " ".join(my_data[my_data['Result']=='Unhappy']['review'])

# Plotting the Happy cloud
plt.figure(figsize=(10, 5))
cloud1 = WordCloud(background_color='white').generate(all_happy_text)
plt.imshow(cloud1)
plt.title("Common Happy Words")
plt.axis('off')
plt.show()

# Plotting the Unhappy cloud
plt.figure(figsize=(10, 5))
cloud2 = WordCloud(background_color='white').generate(all_unhappy_text)
plt.imshow(cloud2)
plt.title("Common Unhappy Words")
plt.axis('off')
plt.show()

# =========================================================
# PRISM PROJECT: EXPERIENCE ANALYSIS DASHBOARD
# Made by: [Your Name/Student ID]
# =========================================================

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import re

# --- STEP 1: LOAD MY DATA ---
# This brings the CSV file into our Python environment
my_data = pd.read_csv('customer_reviews (1).csv')

# --- STEP 2: SETUP MY KEYWORDS ---
# I created these lists to help the computer find "Happy" vs "Unhappy" feedback
good_words = ['great', 'excellent', 'love', 'fast', 'perfect', 'good', 'best', 'happy', 'amazing', 'nice', 'smooth']
bad_words = ['late', 'crack', 'cheap', 'worst', 'broke', 'waste', 'bad', 'terrible', 'broken', 'slow', 'fragile']

# --- STEP 3: THE ANALYSIS LOGIC ---
# This function reads each review and looks for our keywords
def analyze_review(text):
    text = str(text).lower()
    score = 0

    # Add points for good words
    for word in good_words:
        if word in text:
            score = score + 1

    # Subtract points for bad words
    for word in bad_words:
        if word in text:
            score = score - 1

    if score > 0:
        return 'Satisfied'
    elif score < 0:
        return 'Dissatisfied'
    else:
        return 'Neutral'

# Applying the logic to our data
my_data['Status'] = my_data['review'].apply(analyze_review)

# --- STEP 4: CALCULATING KPI NUMBERS ---
total_count = len(my_data)
average_stars = my_data['rating'].mean()
satisfied_count = len(my_data[my_data['Status'] == 'Satisfied'])
satisfaction_rate = (satisfied_count / total_count) * 100

# --- STEP 5: SHOWING KPI CARDS ---
# These are the big numbers at the top of my dashboard
fig_kpi = go.Figure()

fig_kpi.add_trace(go.Indicator(
    mode = "number", value = total_count,
    title = {"text": "Total Feedback"},
    domain = {'x': [0, 0.3], 'y': [0, 1]}))

fig_kpi.add_trace(go.Indicator(
    mode = "number", value = average_stars,
    title = {"text": "Avg Star Rating"},
    domain = {'x': [0.35, 0.65], 'y': [0, 1]}))

fig_kpi.add_trace(go.Indicator(
    mode = "number", value = satisfaction_rate,
    number = {'suffix': "%"},
    title = {"text": "Success Rate"},
    domain = {'x': [0.7, 1], 'y': [0, 1]}))

fig_kpi.update_layout(height=250, title="PRISM EXPERIENCE SUMMARY")
fig_kpi.show()

# --- STEP 6: CHARTS AND VISUALS ---

# 1. Pie Chart for overall mood
fig1 = px.pie(my_data, names='Status', title='Overall Customer Mood',
             color='Status', color_discrete_map={'Satisfied':'green', 'Dissatisfied':'red', 'Neutral':'gray'})
fig1.show()

# 2. Bar Chart for Product Performance
product_stats = my_data.groupby('product')['rating'].mean().reset_index()
fig2 = px.bar(product_stats, x='product', y='rating', title='Which Product has the Best Rating?', color='product')
fig2.show()

# 3. Histogram for Age Groups
fig3 = px.histogram(my_data, x='age', color='Status', title='Feedback Trends by Age',
                   color_discrete_map={'Satisfied':'green', 'Dissatisfied':'red', 'Neutral':'gray'})
fig3.show()

# --- STEP 7: WORD CLOUDS (Common Themes) ---
satisfied_text = " ".join(my_data[my_data['Status']=='Satisfied']['review'])
dissatisfied_text = " ".join(my_data[my_data['Status']=='Dissatisfied']['review'])

plt.figure(figsize=(15, 6))

# Happy WordCloud
plt.subplot(1, 2, 1)
cloud_green = WordCloud(background_color='white', colormap='Greens').generate(satisfied_text)
plt.imshow(cloud_green)
plt.title("Why they are Satisfied")
plt.axis('off')

# Unhappy WordCloud
plt.subplot(1, 2, 2)
cloud_red = WordCloud(background_color='white', colormap='Reds').generate(dissatisfied_text)
plt.imshow(cloud_red)
plt.title("Why they are Dissatisfied")
plt.axis('off')

plt.show()

print("--- Dashboard Generated Successfully ---")

pip install streamlit pandas plotly wordcloud matplotlib

import streamlit as st
import pandas as pd
import plotly.express as px
import re

# 1. Page Settings
st.set_page_config(page_title="Prism Experience Hub", layout="wide")
st.title("📊 PRISM ANALYTICS: Experience Intelligence Hub")
st.markdown("Student Project: Analysis of Customer Feedback and Ratings")

# 2. Loading the File
try:
    # Yahan hum wahi file use kar rahe hain jo aapne di thi
    data = pd.read_csv('customer_reviews (1).csv')

    # 3. Simple Keyword Logic (AI Engine)
    good_words = ['great', 'excellent', 'love', 'fast', 'perfect', 'good', 'best', 'happy', 'amazing', 'nice']
    bad_words = ['late', 'crack', 'cheap', 'worst', 'broke', 'waste', 'bad', 'terrible', 'broken', 'slow']

    def get_status(text):
        text = str(text).lower()
        score = 0
        for word in good_words:
            if word in text: score += 1
        for word in bad_words:
            if word in text: score -= 1

        if score > 0: return 'Satisfied'
        elif score < 0: return 'Dissatisfied'
        else: return 'Neutral'

    data['Status'] = data['review'].apply(get_status)

    # 4. Top KPI Cards (Numbers at the top)
    total = len(data)
    avg_stars = data['rating'].mean()
    sat_perc = (len(data[data['Status'] == 'Satisfied']) / total) * 100

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Reviews", total)
    col2.metric("Average Rating", f"{avg_stars:.1f}")
    col3.metric("Success Rate", f"{sat_perc:.1f}%")

    st.divider()

    # 5. Charts Row
    c_left, c_right = st.columns(2)

    with c_left:
        # Pie Chart: Customer Mood
        fig1 = px.pie(data, names='Status', title='Overall Customer Mood',
                     color='Status', color_discrete_map={'Satisfied':'green', 'Dissatisfied':'red', 'Neutral':'gray'})
        st.plotly_chart(fig1, use_container_width=True)

    with c_right:
        # Bar Chart: Product Performance
        prod_data = data.groupby('product')['rating'].mean().reset_index()
        fig2 = px.bar(prod_data, x='product', y='rating', title='Ratings by Product Category',
                     color='rating', color_continuous_scale='RdYlGn')
        st.plotly_chart(fig2, use_container_width=True)

    # 6. Age Group Analysis
    st.subheader("Demographic Trends (Age vs Feedback)")
    fig3 = px.histogram(data, x='age', color='Status', barmode='group',
                       title="How different ages feel about our service",
                       color_discrete_map={'Satisfied':'green', 'Dissatisfied':'red', 'Neutral':'gray'})
    st.plotly_chart(fig3, use_container_width=True)

    # 7. Simplified "What People are Saying" (No WordCloud needed)
    st.subheader("💡 Key Feedback Highlights")
    st.write("Top words found in the reviews:")

    col_a, col_b = st.columns(2)
    with col_a:
        st.success("Common Happy Words")
        st.write(", ".join(good_words[:6])) # Sirf pehle 6 words dikhayega

    with col_b:
        st.error("Common Complaints")
        st.write(", ".join(bad_words[:6]))

except Exception as e:
    st.error("Error: File 'customer_reviews (1).csv' nahi mil rahi.")
    st.info("Check kijiye ki aapne file ko wahi rakha hai jahan app.py hai.")